apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: dotnet-app
  labels:
    app: dotnet-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http